Upgrade TypeScript, CI config and support Layer type inference.
yoskeoka/convnetjs-ts pull request #1
Opened 2021-02-23 05:43 UTC by Losses

Say, we have a net, and do following operation:

```
const layer = net.layers[0];
if (layer.layer_type === 'conv') {
  layer
}
```

In previous version, layer will always be ILayer, but TypeScript could automatically inference it from its typing.

With this pull request, the type of `layer` will become `ConvLayer`, which is more detailed.

2021-02-23 08:37 UTC, Losses commented
And following commits will improve the typing of "fromJSON" and "toJSON".

2021-02-24 00:57 UTC, Losses commented
Folling commits will export useful types for developers.

2021-02-26 01:08 UTC, Losses commented
@yoskeoka Hmmmmm... Hello?

2021-02-26 08:22 UTC, yoskeoka requested changes
Looks great work.

Please fix some.

- Run CI with node v14 as you specify in `devDependencies`.
- Switch `yarn` to `npm`. Generate lock file with `package-lock.json` filename.
- `test/NeuralNet.spec.ts` throws error with `yarn test` command.

2021-02-26 08:22 UTC, yoskeoka commented on .travis.yml
> +  - "10"
Why wouldn't you use "14" ?
In `package.json` , "@types/node" is specified 14.

2021-02-26 09:00 UTC, Losses commented
@yoskeoka Fixed, please check the code

2021-02-26 09:03 UTC, yoskeoka commented
@Losses 
LGTM!!

2021-02-26 09:03 UTC, yoskeoka approved these changes

2021-02-26 09:03 UTC, merged